name: CI

on:
  push:
    branches:
      - main

jobs:
  call-central-ci:
    uses: "Ooops-Studio/.github/.github/workflows/ci.yml@main"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}