name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  call-central-release:
    uses: Ooops-Studio/.github/workflows/release.yml@main
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}