name: Release

on:
  pull_request:

jobs:
  call-central-release:
    uses: "Ooops-Studio/.github/.github/workflows/release.yml@main"
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}